[package]
name = "game-of-life"
version = "1.0.0"
edition = "2021"
description = "A very minimalistic version of Conway's 'Game of Life'."

[dependencies]
macroquad = "0.4"
rand = "0.8.5"
rayon = "1.10.0"
image = "0.25.1"
